### ISSUE TITLE
Generar el plan de pruebas

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/audiophone-core#13]
Se necesita un plan de pruebas para test de la aplicacion y ejecutarse, antes de la salida a producción.

Si los valores son aceptables, se pasará a produccion la app, despues de aplicacion del diseño.

**Comment by Martalf** [comment]
Este plan de pruebas sigue en pie? antes de montar la app en el equipo productivo?

**Comment by Martalf** [comment]
Se cierra esta actividad, ya se está desplegando la app en producción local de una maquina de 32bit
